import { NextResponse } from "next/server";
import { adminDb, canStaffAccessRecord, verifyStaffRequest } from "@/lib/server/firebaseAdmin";
import { createAndUploadReportPdf } from "@/lib/server/reportServer";


export const runtime = "nodejs";
export async function POST(request, { params }) {
  try {
    const actor = await verifyStaffRequest(request);
    const { reportId } = await params;
    const snapshot = await adminDb.collection("monthlyReports").doc(reportId).get();
    if (!snapshot.exists) return NextResponse.json({ error: "Monthly report was not found." }, { status: 404 });
    const report = { id: snapshot.id, ...snapshot.data() };
    if (!canStaffAccessRecord(actor, report)) return NextResponse.json({ error: "You are not authorised to generate this PDF." }, { status: 403 });
    if (report.status !== "completed") return NextResponse.json({ error: "Complete the report before generating the final PDF." }, { status: 422 });

    const pdf = await createAndUploadReportPdf(report, {
      reportId,
      publishedVersion: report.version || 1,
      versionId: null
    });
    await adminDb.collection("monthlyReports").doc(reportId).set({
      ...pdf,
      pdfIsStale: false,
      pdfInvalidatedAt: null,
      pdfInvalidationReason: null,
      updatedAt: new Date()
    }, { merge: true });
    await adminDb.collection("activityLogs").add({
      recordType: "monthly_report",
      recordId: reportId,
      reportId,
      investorId: report.investorId || null,
      advisorUid: report.advisorUid || actor.uid,
      action: "monthly_report_pdf_generated",
      title: "Monthly report PDF generated",
      description: `${report.title || "Monthly report"} PDF was generated by ${actor.fullName || actor.email}.`,
      createdByUid: actor.uid,
      createdByName: actor.fullName || actor.email,
      createdAt: new Date()
    });
    return NextResponse.json({ success: true, ...pdf });
  } catch (error) {
    console.error("Report PDF generation failed", error);
    return NextResponse.json({ error: error.message || "Unable to generate report PDF." }, { status: 500 });
  }
}
