"use client";

import { useEffect, useMemo, useState } from "react";
import { Download, FileSpreadsheet, ShieldCheck, Upload } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { subscribeInvestors } from "@/services/assessmentService";
import { importInsuranceWorkbook, previewInsuranceWorkbook } from "@/services/insuranceService";
import InsuranceProtectionPanel from "@/components/insurance/InsuranceProtectionPanel";

export default function InsuranceProtectionCentre({ initialInvestorId = "" }) {
  const { profile } = useAuth();
  const [investors, setInvestors] = useState([]); const [investorId, setInvestorId] = useState(initialInvestorId);
  const [file, setFile] = useState(null); const [preview, setPreview] = useState(null); const [working, setWorking] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [refreshKey, setRefreshKey] = useState(0);
  useEffect(() => { if (!profile?.id) return; return subscribeInvestors(profile, (rows) => { setInvestors(rows); setInvestorId((current) => current || initialInvestorId || rows[0]?.id || ""); }, (e) => setError(e.message || "Investors could not be loaded.")); }, [profile, initialInvestorId]);
  const investor = useMemo(() => investors.find((item) => item.id === investorId) || null, [investors, investorId]);
  const doPreview = async () => { if (!investorId || !file) return; setWorking(true); setError(""); setMessage(""); try { setPreview(await previewInsuranceWorkbook(investorId, file)); } catch (e) { setError(e.message); } finally { setWorking(false); } };
  const doImport = async () => { if (!investorId || !file || preview?.errors?.length) return; setWorking(true); setError(""); try { const result = await importInsuranceWorkbook(investorId, file); setMessage(`Imported ${result.imported || 0} policy record(s): ${result.created || 0} new, ${result.updated || 0} updated.`); setPreview(null); setFile(null); setRefreshKey((v) => v + 1); } catch (e) { setError(e.message); } finally { setWorking(false); } };
  return <div className="grid gap-6">
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-start gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-blue-700"><ShieldCheck size={21}/></span><div><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-blue-700">Portfolio Management</p><h1 className="mt-1 font-heading text-3xl font-bold text-slate-950">Insurance & Protection</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Maintain life, health, vehicle, home and other insurance policies, premium dates, renewal dates, documents and reminders. Insurance cover never increases investment AUM.</p></div></div></section>
    {error ? <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div> : null}{message ? <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{message}</div> : null}
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="font-heading text-xl font-bold text-slate-950">Investor & bulk upload</h2><div className="mt-4 grid gap-4 lg:grid-cols-[minmax(240px,1fr)_2fr]">
      <label className="grid gap-1.5 text-sm font-semibold text-slate-700"><span>Investor</span><select value={investorId} onChange={(e) => { setInvestorId(e.target.value); setPreview(null); }} className="min-h-11 rounded-lg border border-slate-200 bg-white px-3"><option value="">Select investor</option>{investors.map((item) => <option key={item.id} value={item.id}>{item.fullName || item.name} {item.clientCode ? `· ${item.clientCode}` : ""}</option>)}</select></label>
      <div className="rounded-xl border border-blue-100 bg-blue-50/40 p-4"><div className="flex flex-wrap items-center gap-2"><a href="/templates/GrowVest_Insurance_Policy_Template_v0.33.3.xlsx" download className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-blue-200 bg-white px-3 text-sm font-bold text-blue-700"><Download size={15}/> Blank template</a><a href="/templates/GrowVest_Insurance_Policy_Filled_Sample_v0.33.3.xlsx" download className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-blue-200 bg-white px-3 text-sm font-bold text-blue-700"><FileSpreadsheet size={15}/> Filled sample</a><a href="/guides/GrowVest_Manual_Investment_and_Insurance_Guide_v0.33.3.docx" download className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 text-sm font-bold text-slate-700"><Download size={15}/> Explanatory guide</a></div><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input type="file" accept=".xlsx,.xls" onChange={(e) => { setFile(e.target.files?.[0] || null); setPreview(null); }} className="min-h-11 flex-1 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"/><button disabled={!file || !investorId || working} onClick={doPreview} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-slate-900 px-4 text-sm font-bold text-white disabled:opacity-50"><Upload size={16}/>{working ? "Checking…" : "Preview & validate"}</button></div></div>
    </div>{preview ? <div className="mt-4 rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-bold text-slate-900">{preview.summary?.rows || 0} valid rows · {preview.summary?.new || 0} new · {preview.summary?.update || 0} updates · {preview.summary?.warnings || 0} warnings · {preview.summary?.errors || 0} errors</p><button disabled={working || preview.errors?.length} onClick={doImport} className="min-h-10 rounded-lg bg-[#1F4ED8] px-4 text-sm font-bold text-white disabled:opacity-40">{working ? "Importing…" : "Import policies"}</button></div>{preview.errors?.length ? <div className="mt-3 rounded-lg bg-red-50 p-3 text-xs font-semibold text-red-700">{preview.errors.slice(0,8).map((item) => <p key={`${item.rowNumber}-${item.message}`}>Row {item.rowNumber || "—"}: {item.message}</p>)}</div> : null}{preview.warnings?.length ? <div className="mt-3 rounded-lg bg-amber-50 p-3 text-xs font-semibold text-amber-800">{preview.warnings.slice(0,8).map((item) => <p key={`${item.rowNumber}-${item.message}`}>Row {item.rowNumber || "—"}: {item.message}</p>)}</div> : null}<div className="mt-3 overflow-x-auto"><table className="min-w-full text-left text-xs"><thead><tr className="border-b border-slate-200 text-slate-500"><th className="py-2 pr-4">Row</th><th className="py-2 pr-4">Type</th><th className="py-2 pr-4">Plan</th><th className="py-2 pr-4">Policy</th><th className="py-2 pr-4">Action</th></tr></thead><tbody>{(preview.rows || []).slice(0,20).map((row) => <tr key={row.rowNumber} className="border-b border-slate-100"><td className="py-2 pr-4">{row.rowNumber}</td><td className="py-2 pr-4 font-semibold">{row.insuranceType}</td><td className="py-2 pr-4">{row.productName}</td><td className="py-2 pr-4">{row.policyNumber}</td><td className="py-2 pr-4 font-bold text-blue-700">{row.match}</td></tr>)}</tbody></table></div></div> : null}</section>
    {investor ? <InsuranceProtectionPanel key={`${investor.id}-${refreshKey}`} investor={investor} editable /> : <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">Select an investor to manage insurance protection.</div>}
  </div>;
}
